general markdown fixes on mint page
cardano-foundation/developer-portal pull request #196
Opened 2021-07-28 17:41 UTC by nothingalike

## Quickfix

I noticed there were some markdown syntax issues on the docs/minting page.

2021-07-28 17:55 UTC, katomm reviewed
Well spotted, my only concern is that you wiped out all of the note boxes.

2021-07-28 20:28 UTC, nothingalike commented
@katomm were formatted that way on purpose? It just looked like more syntax errors. I can revert if that was intentional

2021-07-28 20:43 UTC, katomm commented
The note boxes? Yes. Please see https://developers.cardano.org/docs/portal-style-guide#admonitions for details.

2021-07-28 22:12 UTC, nothingalike commented
Gotcha. Ill see what i can do because that's definitely not rendering as the documentation is showing

2021-07-28 22:40 UTC, rdlrt requested changes
Thanks for the contribution. The admonitions were correct for docusaurus as per style guide. The syntax highlighting for code section was indeed wrong, but would be good to fix other instances on the minting page too

2021-07-28 22:40 UTC, rdlrt commented on docs/native-tokens/minting.md
> -:::note
This should not be changed, as it represents "Note" admonition as per [style guide](https://developers.cardano.org/docs/portal-style-guide#admonitions)

2021-07-28 22:40 UTC, rdlrt commented on docs/native-tokens/minting.md
> -:::note
Same as previous comment

2021-07-28 22:40 UTC, rdlrt commented on docs/native-tokens/minting.md
> -Depending on the size and amount of native assets you are going to send it might be possible to send more than the minimum requirement of only 1 ada. For this guide, we will be sending 10 ada to be o
Same as previous comment

2021-07-28 22:40 UTC, rdlrt commented on docs/native-tokens/minting.md
> -:::note
Same as previous comment

2021-07-28 22:40 UTC, rdlrt commented on docs/native-tokens/minting.md
> -:::note
Same as previous comment

2021-07-29 00:33 UTC, nothingalike commented
@katomm @rdlrt I reverted my changes. Any idea why its not rendering as show in reference?

2021-07-29 00:40 UTC, nothingalike commented
Ok found more bash syntax issues, but i see why i thought things were not rendering correctly. my apologies. everything should be good now

2021-07-29 05:12 UTC, rdlrt approved these changes

2021-07-29 06:22 UTC, katomm approved these changes
Thank you @nothingalike

2021-07-29 06:23 UTC, katomm commented
> but i see why i thought things were not rendering correctly. 

I am curious what the problem was @nothingalike.

2021-07-29 10:27 UTC, nothingalike commented
@katomm  It was the additional code syntax issues i found.

2021-07-29 10:58 UTC, tweakch approved these changes

2021-07-29 16:56 UTC, merged