Request to add Politikoz to the ShowCase
cardano-foundation/developer-portal pull request #206
Opened 2021-08-02 09:46 UTC by thiagosenechal

👋👋 Hello there! Welcome. Please follow the steps below to tell us about your contribution.

1. Select **one of the templates below** that fits your contribution
2. Remove this text as well as the other templates
3. Fill in all sections of the template
4. Summon a reviewr using @mentions (optional)
5. Click "Create pull request"

---

## Showcase addition

* Name: *Project name*
* Description: *Describe your project* (See [Showcase guidelines](CONTRIBUTING/#showcase))
* Link:   <link_to_project>
* Source: <link_to_source_code>
* Tags:
  * `analytics`
  * `explorer`
  * `educational`
  * `game`
  * `gateway`
  * `opensource`
  * `pooltool`
  * `metadata`
  * `nativetoken`
  * `nft`
  * `wallet`

 

---

## Updating documentation

#### Issue

Fixes #issueId

#### Description of the change

---

## Bugfix

Fixes #issueId

#### Description

 

---

## Quickfix

2021-08-02 09:49 UTC, katomm requested changes
We appreciate it if you fill out the PR template and don't paste it unedited.

2021-08-02 10:03 UTC, thiagosenechal commented
> We appreciate it if you fill out the PR template and don't paste it unedited. Thank you.

Sorry for that!

2021-08-03 11:08 UTC, Mercurial approved these changes

2021-08-03 18:43 UTC, katomm approved these changes
Looks good. Thank you for your contribution.

2021-08-04 05:30 UTC, rdlrt approved these changes

2021-08-04 14:26 UTC, merged