Add Python Module
cardano-foundation/developer-portal pull request #220
Opened 2021-08-06 19:03 UTC by emesik

This PR adds Python Module to Builder Tools page. All details are already in the source code.

2021-08-07 00:18 UTC, rdlrt commented
Thanks for the contribution, it seems the codebase being referred is skeleton at the moment for work you'll be doing. Having a section here would require you to have a fully functional release before it can be included.

2021-08-07 07:23 UTC, emesik commented
It is already usable module that might be used by developers right away. They are the target audience.

The project was intended to run on private wallets from the very beginning. It's not a public service, although it might be used to build such, as it provides useful tools that offer higher abstraction layer.

2021-08-07 07:46 UTC, rdlrt commented
> The project was intended to run on private wallets from the very beginning

Thanks for clarifying, in that case - can I request you to add "using cardano-wallet instance" to description?

Just some background on request : Currently there are a lot of projects trying to incorrectly use libraries they find online against API and end up starting to build public service using wallet backend (incl. some that are not supposed to be custodial). Having that clarity on description helps safeguard any future complains on text on developers.cardano.org.

2021-08-07 11:38 UTC, rdlrt approved these changes

2021-08-07 18:29 UTC, katomm requested changes
Hello and thank you very much for the contributions.

Please allow me to request two changes:

- you must not set the "featured" flag yourself.
- you can not set the "getstarted" flag without having a "get started"-page in the portal. Please see the other builder tools with a get started page in the portal as an example, but we need to make this concept clearer in the future.

Thank you.

2021-08-08 00:19 UTC, rdlrt requested changes

2021-08-08 00:19 UTC, rdlrt commented on src/data/builder-tools.js
> +    getstarted: "https://cardano-python.readthedocs.io/en/latest/",
This should change to `null` as in example above

2021-08-08 09:02 UTC, rdlrt approved these changes

2021-08-15 05:15 UTC, Mercurial approved these changes

2021-08-16 09:38 UTC, katomm approved these changes
Thank you for your contributions @emesik!

2021-08-16 09:38 UTC, merged