Update cardano-key-pairs.md
cardano-foundation/developer-portal pull request #539
Opened 2022-03-06 13:34 UTC by D3vJohn

Improved the language.

2022-03-07 08:49 UTC, katomm requested changes
Thank you for taking the time. Unfortunately, a few important tags were deleted. (single backticks for the codeblocks)

`keyname.vkey` vs 'keyname.vkey' vs 'keyname.vkey,'. Could you look into this please?

2022-03-07 09:59 UTC, rdlrt commented on docs/operate-a-stake-pool/cardano-key-pairs.md
> +Cardano cryptographic keys are made up of 'ed25519' key pairs, which include a 'public verification key file' and a'secret (private) key file.' The public key file is commonly referred to as 'keyname
the use of tilde sign helps visibility on the rendered page, compare to single quotes, other than that - all good

2022-03-07 10:59 UTC, D3vJohn reviewed
Added code tags in the appropriate places.

2022-03-09 14:47 UTC, katomm approved these changes
Thank you!




[15:25](https://cardano-ambassadors.slack.com/archives/D02K1MDS7ML/p1646835935281389)
Next translator call is March 16





[15:26](https://cardano-ambassadors.slack.com/archives/D02K1MDS7ML/p1646835960084149)
Oh, I think this email was fired because the time slightly changed on that date because of a clash

2022-03-09 14:49 UTC, merged