Tangocrypto
cardano-foundation/developer-portal pull request #619
Opened 2022-05-18 04:36 UTC by javiertc

👋👋 Hello there! Welcome. Please follow the steps below to tell us about your contribution.

1. Select **one of the templates below** that fits your contribution
2. Remove this text as well as the other templates
3. Fill in all sections of the template
4. Summon a reviewr using @mentions (optional)
5. Click "Create pull request"

---

## Showcase addition

* Name: *Project name*
* Description: *Describe your project* (See [Showcase guidelines](CONTRIBUTING/#showcase))
* Link:   <link_to_project>
* Source: <link_to_source_code>
* Tags:
  * `analytics`
  * `explorer`
  * `educational`
  * `game`
  * `gateway`
  * `opensource`
  * `pooltool`
  * `metadata`
  * `nativetoken`
  * `nft`
  * `wallet`

 

---

## Updating documentation

#### Issue

Fixes #issueId

#### Description of the change

---

## Bugfix

Fixes #issueId

#### Description

 

---

## Quickfix

2022-05-19 15:49 UTC, javiertc commented
Hi @katomm are able to build that branch locally without any issue.

2022-05-20 17:42 UTC, javiertc commented
Hi @katomm can we get an update on this? I've seen approvals to PRs made after this one was submitted. Why the process of adding information to the Cardano developer portal is so slow and cumbersome?

2022-05-20 17:49 UTC, leobel commented
> It's unfortunate that we currently have the deployment previews turned off as we face a problem with Netlify but when I checked out the branch it did not build. (I don't have the error message) Can anyone confirm?

It din't build but you don't have any error message to provide us? We'd like some feedback in order to check the possible error and get this PR approved

2022-05-21 01:06 UTC, rdlrt requested changes
While I find tangocrypto to be a welcome addition, just a couple of minor claims/wording and potentially a reference to under construction feature needs to be addressed in my view

2022-05-21 01:14 UTC, javiertc commented on docs/get-started/tangocrypto.md
> +- There's no way to access the information on a blockchain without using a node.
Hi @rdlrt, what part is not true about the claim? We say "we provide a suite of high availability APIs and developer tools ..." we don't say we are the only one providing it. 

And the second one is also true, you need a cardano node in order to access the information, we are not saying we are the only providers.

2022-05-21 01:25 UTC, javiertc commented on docs/get-started/tangocrypto.md
> +![alt text](../../static/img/get-started/tangocrypto/nftstudio.png)
The API is going to be released this week, that's why we submitted it because we know the process of being incorporated into the portal takes time.

2022-05-21 01:31 UTC, javiertc commented on docs/get-started/tangocrypto.md
> +- There is not a single platform with all the tools most businesses need, leading to multiple platform hiring and cost increase.
It says "all the tools most businesses need", it doesn't s say all the tools. You have to read the whole sentence making emphasis where it says **most**, so it doesn't include all. We are not saying "all the tools that all the business needs", which is the way you are reading it.

2022-05-21 02:14 UTC, rdlrt commented on docs/get-started/tangocrypto.md
> +![alt text](../../static/img/get-started/tangocrypto/nftstudio.png)
I am referring to the image placement for NFT Studio 🙂

2022-05-21 02:16 UTC, javiertc commented on docs/get-started/tangocrypto.md
> +![alt text](../../static/img/get-started/tangocrypto/nftstudio.png)
Ok we can remove the image, no problem.

2022-05-21 02:18 UTC, rdlrt commented on docs/get-started/tangocrypto.md
> +![alt text](../../static/img/get-started/tangocrypto/nftstudio.png)
Thanks, can add it back as soon as that feature is live 👍🏻

2022-05-21 02:21 UTC, rdlrt commented on docs/get-started/tangocrypto.md
> +- There's no way to access the information on a blockchain without using a node.
Sorry, the only text I was referring to was:

> - There's no way to access the information on a blockchain without using a node.

It's not a biggy tho, can leave it in if you strongly agree 🙂

2022-05-21 02:54 UTC, javiertc commented on docs/get-started/tangocrypto.md
> +- There's no way to access the information on a blockchain without using a node.
If you can explain why you don't agree that would be helpful. According to my understanding blockchains are closed networks and the only way to access them is through a node that is part of the blockchain. Thus, if you want to get information from the blockchain you can deploy your own node or use a node provider who exposes the information as an API. What are we getting wrong here?

2022-05-21 03:12 UTC, rdlrt commented on docs/get-started/tangocrypto.md
> +- There's no way to access the information on a blockchain without using a node.
> or use a node provider who exposes the information as an API.

That's the part that's missing as text only contains getting information from node. I get that in individual context, you're only talking about tangocrypto - hence, I said it's not a biggy, happy to retain text as-is, the only reason to even mention it was as I was also requesting change already for NFT Studio

2022-05-21 03:45 UTC, javiertc commented
Hi @rdlrt I just updated the doc following your recommendations 👍🏻

2022-05-21 05:28 UTC, rdlrt approved these changes

2022-05-23 09:59 UTC, katomm approved these changes

2022-05-23 09:59 UTC, merged