Add go-ouroboros-network library, add golang tag
cardano-foundation/developer-portal pull request #659
Opened 2022-06-04 18:39 UTC by wolf31o2

## Showcase addition

* Name: *go-ouroboros-network*
* Description: *A Golang implementation of the Cardano Ouroboros network protocol*
* Link:   https://github.com/cloudstruct/go-ouroboros-network
* Source: https://github.com/cloudstruct/go-ouroboros-network
* Tags:
  * `library`
  * `golang`

Signed-off-by: Chris Gianelloni <cgianelloni@cloudstruct.net>

2022-06-04 19:29 UTC, rdlrt requested changes
Awesome addition, just need to define golang tag

2022-06-04 19:29 UTC, rdlrt commented on src/data/builder-tools.js
> +    tags: ["favorite", "library", "golang"],
Needs tag defined [here](https://github.com/cardano-foundation/developer-portal/blob/staging/src/data/builder-tools.js#L56)

2022-06-04 20:07 UTC, rdlrt approved these changes

2022-06-07 15:27 UTC, fill-the-fill approved these changes

2022-06-07 21:17 UTC, wolf31o2 commented
I have 2/3, @katomm can you be the third approver? TIA!

2022-06-07 23:24 UTC, merged