CVM - Cardano Version Manager :)
cardano-foundation/developer-portal pull request #682
Opened 2022-07-05 04:14 UTC by orelvis15

## Showcase addition

* Name: CVM
* Description: Version manager for cardano node
* Link:   [Project](https://github.com/orelvis15/cvm)
* Source: [Source Code](https://github.com/orelvis15/cvm)
* Tags:
  * `opensource`
  * `pooltool`

2022-07-08 10:32 UTC, katomm requested changes
Thank you very much. Looks more like a builder tool to me, opinions on this? My suggestion is also to remove the "ecosystem" tool, it is for websites that map out the ecosystem like https://developers.cardano.org/showcase/?tags=ecosystem

2022-07-15 09:49 UTC, katomm commented
Any update on this @orelvis15?

2022-07-15 12:30 UTC, orelvis15 commented
> Any update on this @orelvis15?

is anything else needed for the merge?

2022-07-15 13:09 UTC, orelvis15 commented
> Any update on this @orelvis15?

I'm ready!, there I uploaded the changes.

2022-07-15 20:32 UTC, rphair requested changes
@orelvis15 the tag you have applied (`pooltool`) puts it into this category of the Showcase for sites showing stake pool data for delegation & analytics purposes, like these: https://developers.cardano.org/showcase/?tags=pooltool

Your tool is for pool _operators_ and should therefore be tagged as @katomm says as a Builder tool but with the `operatortool` tag, like these: https://developers.cardano.org/tools?tags=operatortool

Finally if this is all true then the thumbnail also needs to be moved into the corresponding directory.  By the way, your tool looks great 🤓

2022-07-16 03:50 UTC, orelvis15 commented on src/data/showcases.js
> +    preview: require("./showcase/cvm.png"),
Done!

2022-07-16 03:51 UTC, orelvis15 commented on src/data/showcases.js
> +    tags: ["pooltool"],
Ho, sorry I hadn't noticed! I already left the change ready. @rphair  thanks a lot!

2022-07-16 04:00 UTC, rphair approved these changes
looks good now 👍

2022-07-28 13:57 UTC, katomm approved these changes

2022-07-28 13:59 UTC, merged